name: Run Unit Tests

on:
  pull_request:
    branches:
      - main  # Trigger on any PR targeting the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm  # Cache npm dependencies (alternative: path: node_modules)
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci  # Faster and more reliable than 'npm install' (ensures a clean state)

      - name: Run unit tests
        run: npm run test:ci
